import java.time.*

/*
  Generamos un valor timeInSeconds para darles un nombre único a los recursos
*/
Date now = new Date()
Integer timeInSeconds = now.getTime()
if (timeInSeconds < 0) {
  println("Time is lower than 0: " + timeInSeconds.toString())
  timeInSeconds = (timeInSeconds * -1)
  println("Fixed Time is now: " + timeInSeconds.toString())
}

Boolean removeNetwork = true
Boolean removeEnv = true
Boolean removeDynamo = true
String buildError = ""

/*
  Seteamos la variable GIT_BRANCH en caso de que no exista
*/
if (!env.GIT_BRANCH) {
    echo "NULL VALUE FOR GIT_BRANCH"
    GIT_BRANCH = scm.branches[0].name
}


/*
  Definir valores en base al branch:
    - s3bucket: Bucket que se utiliza para guardar los archivos de SAM
    - doLocal: Utilizado para validar ejecución en entorno local
    - doTests: Utilizado para validar realización de pruebas
    - stackName: Utilizado para darle un nombre al stack de CloudFormation
*/
if (GIT_BRANCH == "origin/develop") {
  s3bucket = "${env.DEVELOP_S3BUCKET_NAME}"
  doLocal = false
  doTests = true
  stackName = "dev"
} else if (GIT_BRANCH == "origin/staging") {
  s3bucket = "${env.STAGING_S3BUCKET_NAME}"
  doLocal = false
  doTests = true
  stackName = "stg"
} else if (GIT_BRANCH == "origin/master") {
  s3bucket = "${env.PRODUCTION_S3BUCKET_NAME}"
  doLocal = false
  doTests = false
  stackName = "prod"
} else {
  doLocal = true
  doTests = true
  s3bucket = null
  stackName = "local"
}


/*
  Esta función limpia el entorno.
    - debugenv: Utilizado para imprimir información acerca del entorno
*/
def cleanUp(debugenv) {
  stage('Clean') {
    deleteDir()
    if (debugenv) {
      sh 'printenv'
    }
  }
}

/*
  Esta función crea/elimina la red en docker
    - action: create o remove
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
*/
def dockerNetwork(action, timeInSeconds) {
  switch(action) {
    case 'create':
      stage('Create Docker Network') {
        sh "docker network create aws-${timeInSeconds}"
      }
      break;
    case 'remove':
      stage('Remove Docker Network') {
        sh "docker network remove aws-${timeInSeconds}"
      }
      break;
  }
}

/*
  Esta función crea/elimina el contenedor con el entorno de build
    - action: create o remove
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doTests: si vamos a hacer tests linkeamos el container de dynamodb
*/
def pythonBuildEnv(action, timeInSeconds, doTests) {
  switch(action) {
    case 'create':
      stage('Create Build Environment') {
        if (doTests) {
          sh "docker container run -e DOCKER_HOST=172.17.0.1:2375 --name python-env-${timeInSeconds} --link dynamodb-${timeInSeconds}:dynamodb --network aws-${timeInSeconds} -di -v /var/lib/jenkins/.aws:/var/lib/jenkins/.aws -v \${PWD}:\${PWD} ${env.ECR_PYTHON}"
        } else {
          sh "docker container run -e DOCKER_HOST=172.17.0.1:2375 --name python-env-${timeInSeconds} --network aws-${timeInSeconds} -di -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/jenkins/.aws:/var/lib/jenkins/.aws -v \${PWD}:\${PWD} ${env.ECR_PYTHON}"
        }
      }
      break;
    case 'remove':
      stage('Remove Build Environment') {
        sh "docker container rm -f python-env-${timeInSeconds}"
      }
      break;
  }
}

/*
  Esta función crea/elimina el contenedor de dynamodb
    - action: create o remove
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doTests: sólo iniciaremos dynamodb si necesitamos hacer tests
*/
def localDynamo(action, timeInSeconds, doTests) {
  switch(action) {
    case 'create':
      stage('Create local dynamodb') {
        if (doTests) {
          sh "docker container run -e DOCKER_HOST=172.17.0.1:2375 -d --network aws-${timeInSeconds} --name dynamodb-${timeInSeconds} --rm amazon/dynamodb-local"
        } else {
          echo "Este entorno no ejecutará tests, por lo que no es necesario iniciar DynamoDB-Local"
        }
      }
      break;
    case 'remove':
      stage('Remove local dynamodb') {
        if (doTests) {
          sh "docker container rm -f dynamodb-${timeInSeconds}"
        } else {
          echo "Este entorno no ejecutó tests, por lo que no es necesario detener DynamoDB-Local (No iniciado)"
        }
      }
      break;
  }
}

/*
  Esta función se utiliza para lanzar las distintas pruebas
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doLocal: para saber si estamos trabajando en un entorno local
    - doTests: sólo lanzaremos las pruebas que así lo requieran
    - testCase: static, unittest o integration
*/
def testApp(timeInSeconds, doLocal, doTests, testCase) {
  switch(testCase) {
    case 'static':
      stage('Run tests 1/2 - Static tests') {
        if (doTests) {
          sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i python-env-${timeInSeconds} /opt/todo-list-aws/tests/run_tests.sh"
        } else {
          echo "Este entorno no ejecutará tests"
        }
      }
      break;
    case 'unittest':
      stage('Run tests 2/2 - unittest') {
        if (doTests) {
          sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i python-env-${timeInSeconds} /opt/todo-list-aws/tests/run_unittest.sh"
        } else {
          echo "Este entorno no ejecutará tests"
        }
      }
      break;
    case 'integration':
      stage('Run integration tests') {
        if (doLocal) {
          sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -w \${PWD} -i python-env-${timeInSeconds} /opt/todo-list-aws/tests/run_integration.sh ${stackName}"
        } else {
          sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -w \${PWD} -i python-env-${timeInSeconds} /opt/todo-list-aws/tests/run_integration.sh ${stackName}"
        }
      }
  }
}

/*
  Esta función se utiliza para crear un symlink en el entorno de build para trabajar en /opt/todo-list-aws
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - source: Directorio de origen (/var/lib/jenkins/wokspace/...)
    - destination: Directorio de destino (/opt/todo-list-aws)
*/
def linkDirectory(timeInSeconds, source, destination) {
  sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -u root python-env-${timeInSeconds} ln -sf ${source} ${destination}"
}

/*
  Esta función se utiliza para iniciar local-api
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doTests: sólo iniciaremos local-api si necesitamos hacer tests
*/
def startLocalApi(timeInSeconds, doTests) {
  stage("Start sam local-api") {
    if (doTests) {
      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -d -w \${PWD} python-env-${timeInSeconds} sed -i 's/timeInSeconds/${timeInSeconds}/g' todos/todoTableClass.py"
      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -d -w \${PWD} python-env-${timeInSeconds} /home/builduser/.local/bin/sam local start-api --region us-east-1 --host 0.0.0.0 --port 8080 --debug --docker-network aws-${timeInSeconds} --docker-volume-basedir \${PWD}"
      // Wait 10 seconds for api to start
      sleep 10
    } else {
      echo "Este entorno no ejecutará tests, por lo que no es necesario iniciar local-api"
    }
  }
}

/*
  Esta función se utiliza para construir la app
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doLocal: para saber si estamos trabajando en un entorno local
    - stackName: para trabajar sobre un stack de CloudFormation
*/
def buildApp(timeInSeconds, doLocal, stackName) {
  stage('Build application') {
    if (!doLocal) {
      sh "mkdir .aws-sam"
      sh "chmod 777 .aws-sam"
      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i -w \${PWD} python-env-${timeInSeconds} /home/builduser/.local/bin/sam build --region us-east-1 --debug --docker-network aws-${timeInSeconds} --parameter-overrides EnvironmentType=${stackName}"
    } else {
      echo "No construiremos la app en un entorno local"
    }
  }
}

/*
  Después de construir la app validamos si el template funciona
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doLocal: para saber si estamos trabajando en un entorno local
*/
def validateApp(timeInSeconds, doLocal) {
  stage('Validate cloudformation template') {
    if (!doLocal) {
      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i -w \${PWD} python-env-${timeInSeconds} /home/builduser/.local/bin/aws cloudformation validate-template --region us-east-1 --template-body file://.aws-sam/build/template.yaml"
    } else {
      echo "No hemos construido una app para validar en un entorno local"
    }
  }
}

/*
  Esta función despliega SAM
    - timeInSeconds: número que se genera para darle un nombre "único" a los recursos
    - doLocal: para saber si estamo trabajando en un entorno local
    - stackName: para trabajar sobre un stack de CloudFormation
*/
def deployApp(timeInSeconds, doLocal, stackName, s3bucket) {
  stage('Deploy application') {
    if (!doLocal) {
      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i -w \${PWD} python-env-${timeInSeconds} /home/builduser/.local/bin/sam deploy --region us-east-1 --debug --force-upload --stack-name todo-list-aws-${stackName} --debug --s3-bucket ${s3bucket} --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EnvironmentType=${stackName}"
    } else {
      echo "No hemos construido ni validado la app en un entorno local para desplegar"
    }
  }
}

/*
  Habilitar logs de Api Gw
*/
def enableApiLogs(timeInSeconds, doLocal, stackName) {
  stage('Enable API GW logs') {
    if (!doLocal) {
      String restApiId = sh(script: "aws cloudformation describe-stacks --stack-name todo-list-aws-${stackName} --query 'Stacks[0].Outputs[?OutputKey==`todoListResourceApiId`].OutputValue' --output text | tr -d '\n'", returnStdout: true)

      sh "docker container exec -e DOCKER_HOST=172.17.0.1:2375 -i python-env-${timeInSeconds} /home/builduser/.local/bin/aws apigateway update-stage \
        --rest-api-id ${restApiId} \
        --stage-name Prod \
        --patch-operations \
          op=replace,path=/*/*/logging/dataTrace,value=true \
          op=replace,path=/*/*/logging/loglevel,value=Info \
          op=replace,path=/*/*/metrics/enabled,value=true"
    }
  }
}

/*
  Función utilizada para hacer debug de errores
    - e: string de excepción
*/
def printFailure(e) {
  println "Failed because of $e"
}


/*
  Comienzo del pipeline
*/
node {
  // Limpiamos el entorno
  cleanUp(true)

  // Obtenemos la última versión del código desde Git
  stage('Checkout') {
    echo 'Checkout SCM'
    //checkout scm
    git branch: GIT_BRANCH,
        credentialsId: 'codecommit',
        url: 'ssh://git@github.com/mvicha/todo-list-aws.git'
  }

  // Descargamos las imágenes de docker que vamos a utilizar
  stage('Pull docker images') {
    sh "docker image pull ${env.ECR_PYTHON}"
    sh "docker image pull amazon/dynamodb-local"
  }

  try {
    try {
      // Creamos la red de docker
      dockerNetwork('create', timeInSeconds)

      try {
        // Iniciamos dynamodb-local
        localDynamo('create', timeInSeconds, doTests)

        try {
          // Iniciamos nuestro entorno de build
          pythonBuildEnv('create', timeInSeconds, doTests)

          try {
            // Creamos symlink del directorio
            linkDirectory(timeInSeconds, WORKSPACE, "/opt/todo-list-aws")

            try {
              // Testeamos el código y realizmos unittests
              testApp(timeInSeconds, doLocal, doTests, 'static')
              testApp(timeInSeconds, doLocal, doTests, 'unittest')

              try {
                // Iniciamos local-api
                startLocalApi(timeInSeconds, doTests)

                try {
                  // Construimos, validamos y desplegamos la app
                  buildApp(timeInSeconds, doLocal, stackName)

                  try {
                    validateApp(timeInSeconds, doLocal)

                    try {
                      deployApp(timeInSeconds, doLocal, stackName, s3bucket)

                      try {
                        enableApiLogs(timeInSeconds, doLocal, stackName)

                        try {
                          // Realizamos integration test
                          testApp(timeInSeconds, doLocal, doTests, 'integration')
                        } catch(ti) {
                          // Si Algo falló mostramos un error
                          printFailure(ti)

                          buildError = 'Integration Test'
                          currentBuild.result = 'FAILURE'
                        }
                      } catch(ea) {
                        // Fallo al construir o desplegar la app
                        printFailure(ea)

                        buildError = 'Enable API Logging'
                        currentBuild.result = 'FAILURE'
                      }
                    } catch(da) {
                      printFailure(da)

                      buildError = 'App Deployment'
                      currentBuild.result = 'FAILURE'
                    }
                  } catch(va) {
                    printFailure(va)

                    buildError = 'App Validation'
                    currentBuild.result = 'FAILURE'
                  }
                } catch(ba) {
                  printFailure(ba)

                  buildError = 'App Building'
                  currentBuild.result = 'FAILURE'
                }
              } catch(e) {
                printFailure(e)

                buildError = 'Local API Create'
                currentBuild.result = 'FAILURE'
              }
            } catch (ts) {
              printFailure(ts)

              buildError = "Test static"
              currentBuild.result = 'FAILURE'
            }
          } catch(ld) {
            printFailure(ld)

            buildError = 'Link Directory'
            currentBuild.result = 'FAILURE'
          }
        } catch(be) {
          print(be)
          removeEnv = false

          buildError = 'Python-Env Create'
          currentBuild.result = 'FAILURE'
        }
      } catch(ldc) {
        printFailure(ldc)
        removeEnv = false
        removeDynamo = false

        buildError = 'DynamoDB Create'
        currentBuild.result = 'FAILURE'
      }
    } catch(dn) {
      printFailure(dn)
      removeNetwork = false
      removeEnv = false
      removeDynamo = false

      buildError = 'Docker Network Create'
      currentBuild.result = 'FAILURE'
    }

  } finally {
    if (removeEnv) {
      // Siempre eliminamos el entorno de build
      pythonBuildEnv('remove', timeInSeconds, doLocal)
    }

    if (removeDynamo) {
      // Siempre eliminamos dynamodb-local
      localDynamo('remove', timeInSeconds, doTests)
    }

    if (removeNetwork) {
      // Siempre eliminamos la red de docker
      dockerNetwork('remove', timeInSeconds)
    }

    // Limpiamos el entorno
    cleanUp(false)
  }
}
