AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-aws

  todo-list-aws lambda-dynamodb-sam solution

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  todoListAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: staging
      Tags:
      - Key: env
        Value: staging
  todoListFcnList:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: list.list
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        list:
          Type: Api
          Properties:
            Path: /todos/
            Method: get
            RestApiId:
              Ref: todoListAPI
  todoListFcnGet:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: get.get
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        get:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: get
            RestApiId:
              Ref: todoListAPI
  todoListFcnTranslate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: translate.translate
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      - TranslateReadOnly
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        translate:
          Type: Api
          Properties:
            Path: /todos/{id}/{target_language}
            Method: get
            RestApiId:
              Ref: todoListAPI
  todoListFcnCreate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: create.create
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        create:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/
            Method: post
            RestApiId:
              Ref: todoListAPI
  todoListFcnCreateTable:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: createTable.createTable
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        create:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/createTable/
            Method: get
            RestApiId:
              Ref: todoListAPI
  todoListFcnUpdate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: update.update
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        update:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: put
            RestApiId:
              Ref: todoListAPI
  todoListFcnDelete:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: delete.delete
      Runtime: python3.8
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TodoDynamoDbTable
      Events:
        delete:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: delete
            RestApiId:
              Ref: todoListAPI
  # todoListFcnTest:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: todos/
  #     Handler: test_functions.functions
  #     Environment:
  #       Variables:
  #         stgname: "staging"
  #         svcname: "useless"
  #     Events:
  #       Path: /todos/runfulltesting
  #       Method: get
  #       Private: true
  TodoDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  todoListAPI:
    Description: "API ID"
    Value: !GetAtt todoListAPI.RootResourceId
  todoListServerLessAPI:
    Description: "API Gateway endpoint URL for Prod stage for todo-list-aws function"
    # Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Value: !Sub "https://${todoListAPI.RootResourceId}.execute-api.${AWS::Region}.amazonaws.com/${todoListAPI.StageName}"
  todoListServerLessFcnList:
    Description: "List Lambda Function ARN"
    Value: !GetAtt todoListFcnList.Arn
  todoListServerLessFcnGet:
    Description: "Get Lambda Function ARN"
    Value: !GetAtt todoListFcnGet.Arn
  todoListServerLessFcnTranslate:
    Description: "Translate Lambda Function ARN"
    Value: !GetAtt todoListFcnTranslate.Arn
  todoListServerLessFcnCreate:
    Description: "Create Lambda Function ARN"
    Value: !GetAtt todoListFcnCreate.Arn
  todoListServerLessFcnUpdate:
    Description: "Update Lambda Function ARN"
    Value: !GetAtt todoListFcnUpdate.Arn
  todoListServerLessFcnDelete:
    Description: "Delete Lambda Function ARN"
    Value: !GetAtt todoListFcnDelete.Arn
  #todoListServerLessReadOnlyIamRole:
  #  Description: "Implicit IAM Role created for todoListFcnList function"
  #  Value: !GetAtt todoListFcnListRole.Arn

