String gitRepo = "${env.GIT_REPO}"
String branchName = "${env.GIT_BRANCH}"
String ecrDest = "${env.ECR_DEST}"
String credentialsId = "${env.CODECOMMIT_ID}"


pipeline {
  agent any

  stages {
    stage('Clean') {
      steps {
        deleteDir()
        sh 'printenv'
      }
    }
  
    stage('Checkout') {
      steps {
        git branch: branchName,
          credentialsId: "${credentialsId}",
          url: "${gitRepo}"
      }
    }

    stage('Build docker image') {
      steps {
        sh("""
            docker image build -t ${ecrDest} .
            docker image push ${ecrDest}
        """)
      }
    }
  }
}
