pipeline {
    agent any
    stages {
        stage('Clean'){    
            steps {
                deleteDir()
                sh 'printenv'
            }
        }
        stage('Setup Credentials de AWS'){    
            steps {
                deleteDir()
                sh "echo ${env.CREDENTIALS} > /var/lib/jenkins/.aws/credentials"
                writeFile (file: '/var/lib/jenkins/.aws/credentials', text: "${env.CREDENTIALS}")

            }
        }
        stage('Validate Credentials'){    
            steps {
                deleteDir()
                sh "aws s3 ls"
            }
        }
        stage('Validate software'){    
            steps {
                sh 'sam --version'
                sh 'aws --version'
                sh 'python3.8 --version'
                sh 'python3.7 --version'
            }
        }
        stage('Obtención de credenciales para Docker'){
            steps {
                sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${env.ECR_URL}"
            }
        }
    }
}
